---
- hosts: rails
  remote_user: root
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/deploy_user.yml

- hosts: rails   
  remote_user: deploy
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/apt.yml
    - include: tasks/ror.yml
    - include: tasks/security.yml
    - include: tasks/passenger_nginx.yml

- hosts: rails
  remote_user: deploy
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/postgres.yml
