---
- hosts: rails
  remote_user: root
  become: yes
  tasks:
    - include: tasks/deploy_user.yml
  remote_user: deploy
  become: yes
  tasks:
    - include: tasks/apt.yml
    - include: tasks/ror.yml