---
- name: Add the PPA for rvm
  apt_repository: repo=ppa:rael-gc/rvm state=present
  become: yes

- name: get yarn pubkey
  become: yes
  command:  bash -lc "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"

- name: add yarn to apt sources
  become: yes
  command:  bash -lc "echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list"


- name: Update all packages to the latest versions
  sudo: yes
  apt: update_cache=yes

- name: Install Ruby Dependencies
  sudo: yes
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - software-properties-common
    - libffi-dev
    - nodejs
    - yarn
    - rvm
    - postgresql
    - libpq-dev
    - python-psycopg2

