---
# Passenger repository setup.
- name: Add Passenger apt key.
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 561F9B9CAC40B2F7
    state: present

- name: Add apt HTTPS capabilities.
  apt: name=apt-transport-https state=present

- name: Add Phusion apt repo.
  apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main'
    state: present
    update_cache: yes

- name: Install Nginx and Passenger.
  apt: "pkg={{ item }} state=present"
  with_items:
    - nginx-core
    - libnginx-mod-http-passenger

# Nginx and passenger configuration.
- name: Copy Nginx configuration into place.
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- name: Ensure passenger virtual host is enabled.
  shell: sudo /usr/bin/passenger-config validate-install
