---
- role: rvm_io.rvm1-ruby
  when: installeer_ruby
  sudo: true
  rvm1_user: '{{rvmuser}}'
  rvm1_rvm_version: 'stable'
  rvm1_rvm_check_for_updates: false
  rvm1_gpg_keys: ''
  rvm1_rubies:
    - 'ruby-1.9.3-p551'
  rvm1_install_flags: '--auto-dotfiles --user-install'
  rvm1_install_path: '/home/{{rvmuser}}/.rvm'

- name: create application folder
  file: 
    path: /var/www/{{ app_name }} 
    state: directory
    owner: deploy
    group: www-data
    mode: 0775
    recurse: yes

- name: create application files
  copy:
    content: ""
    dest: /var/www/D-pressed/shared/config/{{ item }}
  with_items:
    - database.yml
    - master.key
    - secrets.yml

- name: copy files to server
  copy:
    src: ../D-pressed/config/{{ item }}
    dest: /var/www/D-pressed/shared/config/{{ item }}
  with_items:
    - database.yml
    - master.key
